name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm install
      - run: npm run build
      - run: npx gh-pages -d dist -b master -u "GitHub Actions <bots@github.com>" -t -f
          -r https://${{ secrets.CODING_TOKEN }}@e.coding.net/zce/playground/m2i.git
